"use client";

import Link from "next/link";
import { BookOpen, ChevronRight, Settings } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { useSearchParams } from "next/navigation";
import { BottomNav, Card } from "@/components/ui";
import { PhoneShell } from "@/components/phone-shell";
import { parseDashboardRange } from "@/lib/design-filters";
import { addDaysToDateInputValue, formatShortDate, getJstWeekStartInputValue, toJstDateInputValue } from "@/lib/date";
import type { getAllWorkouts } from "@/lib/data";
import { transitionFor } from "@/lib/motion";
import { primaryMuscle, workoutCardioMinutes, workoutSetCount, workoutSummary, workoutTitle, workoutVolume } from "@/lib/workouts";
import { shortMuscleName } from "@/lib/constants";

const labels = ["月", "火", "水", "木", "金", "土", "日"];
const options = [{ value: "today", label: "今日" }, { value: "week", label: "今週" }, { value: "year", label: "今年" }, { value: "all", label: "累計" }] as const;
type Workouts = Awaited<ReturnType<typeof getAllWorkouts>>;
export function DashboardClient({ initialWorkouts }: { initialWorkouts: Workouts }) {
 const searchParams = useSearchParams(); const range = parseDashboardRange(searchParams.get("range") ?? undefined); const reduced = useReducedMotion();
 const workouts = filter(initialWorkouts, range); const volume = workouts.reduce((n,w)=>n+workoutVolume(w),0); const weekly = week(initialWorkouts); const max=Math.max(...weekly.map(x=>x.volume),1);
 const setRange=(next: typeof range)=>{ const p=new URLSearchParams(window.location.search); if(next==="today") p.delete("range"); else p.set("range",next); window.history.replaceState(null,"",`${window.location.pathname}${p.size?`?${p}`:""}${window.location.hash}`); };
 return <PhoneShell nav={<BottomNav active="dashboard"/>}><section className="pt-2"><div className="flex items-start justify-between gap-3"><h1 className="font-display text-display-xl">今日の<span className="text-macho-lime">ワークアウト</span></h1><Link href="/settings/profile" className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-macho-s border border-macho-border text-macho-muted" aria-label="プロフィール設定"><Settings size={17}/></Link></div></section>
 <div className="mt-4 grid grid-cols-4 gap-1 rounded-macho-m border border-macho-border bg-macho-surface p-1">{options.map(o=><button key={o.value} type="button" onClick={()=>setRange(o.value)} aria-pressed={range===o.value} className={`relative flex h-9 items-center justify-center rounded-macho-s text-caption font-semibold ${range===o.value?"text-macho-black":"text-macho-muted"}`}>{range===o.value && (reduced ? <span className="absolute inset-0 rounded-macho-s bg-macho-lime"/> : <motion.span layoutId="dashboard-range-indicator" transition={transitionFor(false)} className="absolute inset-0 rounded-macho-s bg-macho-lime"/>)}<span className="relative z-10">{o.label}</span></button>)}</div>
 <section className="mt-5 grid grid-cols-3 gap-2"><Stat label="記録" value={workouts.length}/><Stat label="種目" value={workouts.reduce((n,w)=>n+w.workout_exercises.length,0)}/><Stat label="セット" value={workouts.reduce((n,w)=>n+workoutSetCount(w),0)}/></section>
 <Card className="mt-2.5 flex items-center justify-between gap-3 px-3.5 py-3"><div><p className="text-label text-macho-muted">{options.find(x=>x.value===range)?.label}のボリューム</p><p className="mt-0.5 font-display text-display-num text-macho-lime">{Math.round(volume).toLocaleString()}<span className="font-sans text-body tracking-normal">kg</span></p></div><div className="text-right"><p className="text-label text-macho-muted">有酸素</p><p className="mt-1 text-body font-semibold">{workouts.reduce((n,w)=>n+workoutCardioMinutes(w),0)}min</p></div></Card>
 <Card className="mt-[18px]"><p className="mb-3.5 text-title font-medium">今週のアクティビティ</p><div className="flex h-20 items-end gap-1.5">{weekly.map(x=>{const h=x.volume?Math.max(18,Math.round(x.volume/max*68)):4; const c=x.key===toJstDateInputValue()?"bg-macho-lime":x.volume?"bg-macho-lime/40":"bg-macho-lime/10";return <div key={x.key} className="flex flex-1 flex-col items-center"><div className={`mb-1.5 w-full rounded-md ${c}`} style={{height:h}}/><span className="text-label text-macho-muted">{x.label}</span></div>})}</div></Card>
 <section className="mt-[18px]"><div className="mb-2.5 flex items-center justify-between"><p className="text-title font-medium">最近の記録</p><Link href="/history" className="text-caption text-macho-lime">すべて見る <ChevronRight size={12} className="inline"/></Link></div>{initialWorkouts.slice(0,3).map(w=>{const m=primaryMuscle(w);return <Card key={w.id} className="mb-2 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-macho-s text-base font-semibold" style={{color:m?.color??"#D4FF00",backgroundColor:`${m?.color??"#D4FF00"}1f`}}>{shortMuscleName(m?.name??"記")}</div><div className="min-w-0 flex-1"><p className="text-body font-medium">{workoutTitle(w).replace("トレーニング","")}</p><p className="truncate text-caption text-macho-muted">{workoutSummary(w)||"記録なし"}</p></div><div className="text-right"><p className="text-label text-macho-muted">{formatShortDate(w.date)}</p><p className="text-caption text-macho-lime">{workoutSetCount(w)?`${workoutSetCount(w)}set`:`${workoutCardioMinutes(w)}min`}</p></div></Card>})}{initialWorkouts.length===0&&<Card className="mb-2 text-center"><p className="text-body font-medium">まだ記録がありません</p><p className="mt-1 text-caption text-macho-muted">記録タブから今日のワークアウトを保存しましょう。</p></Card>}<Link href="/templates" className="mt-3 block"><Card className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-macho-s bg-macho-lime/10 text-macho-lime"><BookOpen size={20}/></div><div className="flex-1"><p className="text-title font-medium">テンプレート</p><p className="text-label text-macho-muted">保存したメニューから記録を開始</p></div><ChevronRight size={16} className="text-macho-muted"/></Card></Link></section></PhoneShell>;
}
function Stat({label,value}:{label:string;value:number}){return <Card className="px-1.5 py-3.5 text-center"><p className="text-label text-macho-muted">{label}</p><p className="font-display text-display-num text-macho-lime">{value}</p></Card>}
function filter(w:Workouts,r:string){const today=toJstDateInputValue();if(r==="today")return w.filter(x=>x.date===today);if(r==="week"){const s=getJstWeekStartInputValue();const e=addDaysToDateInputValue(s,6);return w.filter(x=>x.date>=s&&x.date<=e)}if(r==="year")return w.filter(x=>x.date.startsWith(today.slice(0,4)));return w}
function week(w:Workouts){const monday=getJstWeekStartInputValue();return labels.map((label,i)=>{const key=addDaysToDateInputValue(monday,i);return {label,key,volume:w.filter(x=>x.date===key).reduce((n,x)=>n+workoutVolume(x),0)}})}
